package com.anna.lozytska.achievementstimer.db.modelspec;

import com.yahoo.squidb.annotations.ColumnSpec;
import com.yahoo.squidb.annotations.TableModelSpec;

/**
 * Created by alozytska on 01.08.16.
 */
@TableModelSpec(className="Task", tableName="tasks")
public class TaskSpec {
    // primary key _id is autogenerated
    @ColumnSpec(constraints = "NOT NULL")
    String title;
    String description;
    String imageUrl;
    @ColumnSpec(defaultValue = "0")
    long estimatedTime;
    @ColumnSpec(defaultValue = "0")
    long spentTime;
    @ColumnSpec(defaultValue = "0")
    long parentTaskId;
    @ColumnSpec(defaultValue = "false")
    boolean isAchieved;
}
